### PR TITLE
fix: add missing direct dependency @aws-sdk/url-parser

### PR DESCRIPTION
**Pull request by austinkelleher**
Usage: https://github.com/lifeomic/alpha/blob/db7ccb5cbfbd6636e11e8849598d64bf789276bc/src/interceptors/aws-v4-signature.ts#L3C1-L3C1

### CODE REVIEW

**Comment by austinkelleher** [comment]
cc @DavidTanner @mdlavin

**Review by DavidTanner — APPROVED** [review]

**Comment by shawnzhu** [comment]
FYI: this will avoid the break change when upgrading to @aws-sdk/client-lambda@^2.363.0 (where `@aws-sdk/url-parser` was renamed to `@smithy@url-parser` via https://github.com/aws/aws-sdk-js-v3/pull/4873)

**Comment by swain** [comment]
@austinkelleher Thanks for this PR Austin, and sorry for the delay in feedback.

It looks great. We have a security control that requires all of our commits to be signed + verified (even from the public). Would you be willing to update your commit to be signed?

This Gist provides a straightforward guide for setting up commit signing: https://gist.github.com/Beneboe/3183a8a9eb53439dbee07c90b344c77e

If you'd rather _not_ spend time setting up commit signing, I'm afraid the only option is for us to merge a different PR with the fix here. Happy to make that fix myself, but you'd lose your contribution -- just let me know how you'd like to proceed.

**Comment by swain** [comment]
@austinkelleher Didn't hear back from you on the above, so we went ahead and released the fix via a different PR. Thanks for raising this issue!

The fix is available in version 5.1.3.

**Pull request closed without merging**
