### PR TITLE
Use either V2 or V3 aws sdk

### PR DESCRIPTION
**Pull request by DavidTanner**
dual

With all the issues around `@aws-sdk`, it would be preferable not to force users to pick one, but allow for configuring either one.

Moving the dependencies out of Peer or Deps relies on the consuming library to pick versions.  Less mess that way.

### CODE REVIEW

**Comment by swain** [comment]
How essential is this change? A breaking change to `alpha` is a huge pain to propagate throughout the platform.

**Comment by DavidTanner** [comment]
I'm not sure if it needs to be a breaking change.  It does drop dependencies, but it should work just fine if those deps are listed at the top level.  I don't mind making it a minor bump @swain .

**Comment by rmneidermyer** [comment]
> I think my first comment is confusing -- I'd say this is definitely a breaking change, and we should mark it as one.
> 
> I think I'm missing some context -- could you elaborate a bit more on "all the issues around @aws-sdk"? What are the specific issues we're trying to address with this change?

If we do approach it as a breaking change should we consider a fork in this case and make the transition from v2->v3 explicit? Force alpha consumers to go to a new package when ready. This would avoid the dynamic imports though I am not sure it does anything for the existing bug (UE-85) if v3 consumers can inadvertently use alpha and fail.

**Comment by david-wb** [comment]
Maybe include the aws-sdks as "optional" peer dependencies? E.g.
```
"peerDependencies": { 
  "winston": "> 1.0.0 <= 1.2.10",
  "foo": "~2.3.0"
},
"peerDependenciesMeta": {
  "winston": {
    "optional": true
  }
}
```

**Pull request closed without merging**
